// Code generated by rice embed-go; DO NOT EDIT.
package main

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file3 := &embedded.EmbeddedFile{
		Filename:    "index.html",
		FileModTime: time.Unix(1610243545, 0),

		Content: string(""),
	}
	file5 := &embedded.EmbeddedFile{
		Filename:    "login/index.html",
		FileModTime: time.Unix(1610245601, 0),

		Content: string("<h1>Login Page</h1>"),
	}
	file6 := &embedded.EmbeddedFile{
		Filename:    "login/styles.css",
		FileModTime: time.Unix(1610239757, 0),

		Content: string(""),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1610244269, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file3, // "index.html"

		},
	}
	dir2 := &embedded.EmbeddedDir{
		Filename:   "css",
		DirModTime: time.Unix(1610244269, 0),
		ChildFiles: []*embedded.EmbeddedFile{},
	}
	dir4 := &embedded.EmbeddedDir{
		Filename:   "login",
		DirModTime: time.Unix(1610243534, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file5, // "login/index.html"
			file6, // "login/styles.css"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{
		dir2, // "css"
		dir4, // "login"

	}
	dir2.ChildDirs = []*embedded.EmbeddedDir{}
	dir4.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`ui`, &embedded.EmbeddedBox{
		Name: `ui`,
		Time: time.Unix(1610244269, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"":      dir1,
			"css":   dir2,
			"login": dir4,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"index.html":       file3,
			"login/index.html": file5,
			"login/styles.css": file6,
		},
	})
}
